lang: zh-Hans
source: ./nshipster.cn
url: http://nshipster.cn

title: NSHipster
description: "<strong>NSHipster</strong> 关注被忽略的 Objective-C、Swift 和 Cocoa 特性。每周更新。"
permalink: /:title/
timezone: Asia/Shanghai
lsi: false

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data"]

highlighter: pygments

groups:
  - Cocoa
  - Objective-C
  - Open Source
  - Miscellanea

collections:
  authors:
    output: true
    permalink: /authors/:path/
  translators:
    output: true
    permalink: /translators/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "translators"
    values:
      layout: "translator"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

